/* ================================================================
   APP.JS — Dynamic Learning Hub with Full-Page Post Viewer
   Features: Card grid, full-page article, related posts, sticky TOC,
   reading progress, search, category/level filters, ads, SEO
   ================================================================ */

const STORAGE_KEY = "pipingEpcProjectHubPosts";
const CONTENT_VERSION = 11;

/* ── DOM Elements ────────────────────────────────────── */
const searchInput = document.getElementById("search");
const postsGrid = document.getElementById("posts-grid");
const postCount = document.getElementById("post-count");
const feedTitle = document.getElementById("feed-title");
const homeView = document.getElementById("home-view");
const postView = document.getElementById("post-view");
const heroEl = document.getElementById("hero");
const navbar = document.getElementById("navbar");
const navLinks = document.getElementById("nav-links");
const hamburger = document.getElementById("hamburger");
const readingProgress = document.getElementById("reading-progress");
const backToTop = document.getElementById("back-to-top");

/* Post View Elements */
const pvBack = document.getElementById("pv-back");
const pvBreadcrumb = document.getElementById("pv-breadcrumb");
const pvMeta = document.getElementById("pv-meta");
const pvTitle = document.getElementById("pv-title");
const pvExcerpt = document.getElementById("pv-excerpt");
const pvTags = document.getElementById("pv-tags");
const pvBody = document.getElementById("pv-body");
const pvToc = document.getElementById("pv-toc");
const pvTocMobileList = document.getElementById("pv-toc-mobile-list");
const relatedGrid = document.getElementById("related-grid");
const shareTwitter = document.getElementById("share-twitter");
const shareLinkedin = document.getElementById("share-linkedin");
const shareCopy = document.getElementById("share-copy");

let currentCategory = "All";
let currentLevel = "All";
let currentPostId = null;

/* ── Storage ─────────────────────────────────────────── */
function loadPosts() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  try { const p = JSON.parse(raw); return Array.isArray(p) ? p : []; }
  catch { return []; }
}
function savePosts(posts) { localStorage.setItem(STORAGE_KEY, JSON.stringify(posts)); }

/* ── Load ALL_POSTS from posts-data.js ───────────────── */
function syncPostsFromSource() {
  const existing = loadPosts();
  const autoGen = existing.filter(p => p && p.autoGenerated);
  const sourceMatch = autoGen.every((p, i) => {
    const s = ALL_POSTS[i];
    return s && p.title === s.title && p.excerpt === s.excerpt && p.content === s.content;
  });
  const current = autoGen.length === ALL_POSTS.length &&
    autoGen.every(p => p.contentVersion === CONTENT_VERSION && typeof p.content === "string" && p.content.length > 50) &&
    sourceMatch;
  if (current) return;

  const manual = existing.filter(p => !p.autoGenerated);
  const now = Date.now();
  const regen = ALL_POSTS.map((src, i) => ({
    id: `note-${src.id}-${now}`,
    title: src.title,
    category: src.category,
    tags: src.tags,
    excerpt: src.excerpt,
    content: src.content,
    sourceUrl: src.sourceUrl || "",
    createdAt: src.createdAt || new Date(now - i * 60000).toISOString(),
    level: src.level || "beginner",
    autoGenerated: true,
    contentVersion: CONTENT_VERSION,
  }));
  savePosts([...manual, ...regen]);
}

/* ── Helpers ─────────────────────────────────────────── */
function escapeHtml(t) {
  return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}

function readTime(content) {
  return Math.max(1, Math.ceil((content || "").split(/\s+/).length / 200));
}

function slugify(text) {
  return text.replace(/[^a-zA-Z0-9\s]/g, "").trim().replace(/\s+/g, "-").toLowerCase();
}

/* ── Filters ─────────────────────────────────────────── */
function getFilteredPosts() {
  const q = (searchInput.value || "").trim().toLowerCase();
  return loadPosts()
    .filter(post => {
      if (currentCategory !== "All" && post.category !== currentCategory) return false;
      if (currentLevel !== "All" && (post.level || "beginner") !== currentLevel) return false;
      if (q && !post.title.toLowerCase().includes(q) && !post.excerpt.toLowerCase().includes(q) &&
          !post.content.toLowerCase().includes(q) && !post.tags.join(" ").toLowerCase().includes(q)) return false;
      return true;
    })
    .sort((a, b) => {
      const lo = { beginner: 0, intermediate: 1, advanced: 2 };
      const ld = (lo[a.level] || 0) - (lo[b.level] || 0);
      return ld !== 0 ? ld : new Date(b.createdAt) - new Date(a.createdAt);
    });
}

/* ── Markdown Renderer ───────────────────────────────── */
function markdownToHtml(md) {
  const e = escapeHtml(md || "");

  // Fenced code blocks
  let html = e.replace(/```(\w*)\n?([\s\S]*?)```/g, (_m, lang, code) => {
    const cls = lang ? ` class="lang-${lang}"` : "";
    return `<pre><code${cls}>${code.trim()}</code></pre>`;
  });

  // Headings with IDs
  html = html
    .replace(/^###\s+(.*)$/gm, (_m, t) => `<h3 id="${slugify(t)}">${t}</h3>`)
    .replace(/^##\s+(.*)$/gm, (_m, t) => `<h2 id="${slugify(t)}">${t}</h2>`)
    .replace(/^#\s+(.*)$/gm, "<h1>$1</h1>");

  // Inline
  html = html
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[(.+?)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');

  // Tables
  html = html.replace(
    /(?:^|\n)(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)+)/g,
    (_m, hdr, _sep, body) => {
      const ths = hdr.split("|").filter(Boolean).map(h => `<th>${h.trim()}</th>`).join("");
      const rows = body.trim().split("\n").map(r => {
        const tds = r.split("|").filter(Boolean).map(c => `<td>${c.trim()}</td>`).join("");
        return `<tr>${tds}</tr>`;
      }).join("");
      return `<table><thead><tr>${ths}</tr></thead><tbody>${rows}</tbody></table>`;
    }
  );

  // Ordered lists (1. item)
  html = html.replace(/(?:^|\n)(\d+\.\s+.+(?:\n\d+\.\s+.+)*)/g, chunk => {
    const items = chunk.trim().split("\n")
      .map(l => l.replace(/^\d+\.\s+/, "").trim()).filter(Boolean)
      .map(i => `<li>${i}</li>`).join("");
    return `<ol>${items}</ol>`;
  });

  // Unordered lists
  html = html.replace(/(?:^|\n)(-\s+.+(?:\n-\s+.+)*)/g, chunk => {
    const items = chunk.trim().split("\n")
      .map(l => l.replace(/^-\s+/, "").trim()).filter(Boolean)
      .map(i => `<li>${i}</li>`).join("");
    return `<ul>${items}</ul>`;
  });

  // Blockquotes
  html = html.replace(/(?:^|\n)&gt;\s+(.+)/g, "<blockquote>$1</blockquote>");

  // Paragraphs
  return html.split(/\n\n+/).map(block => {
    const t = block.trim();
    if (!t) return "";
    if (/^<h[1-3]>|^<ul>|^<ol>|^<pre>|^<table>|^<blockquote>/.test(t)) return t;
    return `<p>${t.replace(/\n/g, "<br>")}</p>`;
  }).join("\n");
}

/* ── Extract TOC ─────────────────────────────────────── */
function extractToc(md) {
  const headings = [];
  for (const line of (md || "").split("\n")) {
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);
    if (h3) headings.push({ level: 3, text: h3[1].trim(), id: slugify(h3[1]) });
    else if (h2) headings.push({ level: 2, text: h2[1].trim(), id: slugify(h2[1]) });
  }
  return headings;
}

function renderTocHtml(headings) {
  if (headings.length < 3) return "";
  return `<h4>📋 Table of Contents</h4><ul>${headings.map(h => {
    const cls = h.level === 3 ? ' class="toc-indent"' : "";
    return `<li${cls}><a href="#${h.id}" class="toc-link">${escapeHtml(h.text)}</a></li>`;
  }).join("")}</ul>`;
}

/* ============ HOME VIEW RENDERING ============ */

function renderHome() {
  const posts = getFilteredPosts();
  postCount.textContent = `${posts.length} tutorial${posts.length !== 1 ? "s" : ""}`;

  const categoryLabels = { All: "All Tutorials", JavaScript: "JavaScript Tutorials", Playwright: "Playwright Tutorials", TypeScript: "TypeScript Tutorials", MCP: "MCP Tutorials", TOSCA: "TOSCA Tutorials", Both: "Cross-Topic Tutorials" };
  feedTitle.textContent = categoryLabels[currentCategory] || "All Tutorials";

  postsGrid.innerHTML = "";

  if (posts.length === 0) {
    postsGrid.innerHTML = '<div class="empty-msg" style="grid-column:1/-1;text-align:center;padding:3rem;color:var(--ink-muted)"><p style="font-size:1.2rem">No tutorials match your search.</p><p>Try a different keyword or category.</p></div>';
    return;
  }

  posts.forEach((post, i) => {
    const level = (post.level || "beginner").toLowerCase();
    const levelEmoji = { beginner: "🌱", intermediate: "⭐", advanced: "🚀" };
    const rt = readTime(post.content);

    const card = document.createElement("div");
    card.className = "post-card";
    card.style.animationDelay = `${Math.min(i * 30, 300)}ms`;
    card.innerHTML = `
      <div class="card-meta">
        <span class="card-category cat-${post.category.toLowerCase()}">${escapeHtml(post.category)}</span>
        <span class="card-level lvl-${level}">${levelEmoji[level] || ""} ${level.charAt(0).toUpperCase() + level.slice(1)}</span>
        <span class="card-read-time">📖 ${rt} min</span>
      </div>
      <h3>${escapeHtml(post.title)}</h3>
      <p class="card-excerpt">${escapeHtml(post.excerpt)}</p>
      <div class="card-tags">${post.tags.slice(0, 4).map(t => `<span class="card-tag">#${escapeHtml(t)}</span>`).join("")}</div>
      <span class="card-arrow">→</span>
    `;
    card.addEventListener("click", () => openPost(post));
    postsGrid.appendChild(card);

    // In-feed ad every 6 posts
    if ((i + 1) % 6 === 0 && i < posts.length - 1) {
      const ad = document.createElement("div");
      ad.className = "ad-infeed-card";
      ad.innerHTML = `<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2441085120272132" data-ad-slot="INFEED_SLOT_ID" data-ad-format="fluid" data-ad-layout-key="-6t+ed+2i-1n-4w"></ins>`;
      postsGrid.appendChild(ad);
      try { (window.adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {}
    }
  });
}

/* ============ POST VIEW (FULL PAGE) ============ */

function openPost(post) {
  currentPostId = post.id;

  // Update URL hash for direct linking
  const slug = slugify(post.title);
  history.pushState({ postId: post.id }, post.title, `#post/${slug}`);

  // Update page title for SEO
  document.title = `${post.title} — LearnHub`;

  // Hide home, show post
  homeView.classList.add("hidden");
  heroEl.classList.add("hidden");
  postView.classList.remove("hidden");
  window.scrollTo(0, 0);

  // Breadcrumb
  pvBreadcrumb.innerHTML = `<a href="#" class="breadcrumb-home">Home</a> → <a href="#" class="breadcrumb-cat" data-cat="${escapeHtml(post.category)}">${escapeHtml(post.category)}</a> → <span>${escapeHtml(post.title)}</span>`;

  // Meta
  const level = (post.level || "beginner").toLowerCase();
  const levelLabels = { beginner: "🌱 Beginner", intermediate: "⭐ Intermediate", advanced: "🚀 Advanced" };
  const rt = readTime(post.content);
  const postDate = post.createdAt ? new Date(post.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "";
  pvMeta.innerHTML = `
    <span class="card-category cat-${post.category.toLowerCase()}">${escapeHtml(post.category)}</span>
    <span class="card-level lvl-${level}">${levelLabels[level] || level}</span>
    <span class="card-read-time">📖 ${rt} min read</span>
    ${postDate ? `<span class="card-date">By <strong>Ravi</strong> · ${postDate}</span>` : ""}
  `;

  pvTitle.textContent = post.title;
  pvExcerpt.textContent = post.excerpt;
  pvTags.innerHTML = post.tags.map(t => `<span class="pv-tag">#${escapeHtml(t)}</span>`).join("");

  // Body
  pvBody.innerHTML = markdownToHtml(post.content);

  // TOC
  const headings = extractToc(post.content);
  const tocHtml = renderTocHtml(headings);
  pvToc.innerHTML = tocHtml;
  pvTocMobileList.innerHTML = tocHtml;

  // TOC click handlers (smooth scroll)
  document.querySelectorAll(".toc-link").forEach(link => {
    link.addEventListener("click", e => {
      e.preventDefault();
      const id = link.getAttribute("href").slice(1);
      const target = document.getElementById(id);
      if (target) target.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  });

  // Share links
  const pageUrl = window.location.origin + window.location.pathname + `#post/${slug}`;
  const encodedTitle = encodeURIComponent(post.title);
  const encodedUrl = encodeURIComponent(pageUrl);
  shareTwitter.href = `https://twitter.com/intent/tweet?text=${encodedTitle}&url=${encodedUrl}`;
  shareLinkedin.href = `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`;
  shareCopy.onclick = () => {
    navigator.clipboard.writeText(pageUrl).then(() => {
      shareCopy.textContent = "✅ Copied!";
      setTimeout(() => { shareCopy.textContent = "📋 Copy Link"; }, 2000);
    });
  };

  // Breadcrumb nav
  pvBreadcrumb.querySelector(".breadcrumb-home").addEventListener("click", e => { e.preventDefault(); goHome(); });
  const catLink = pvBreadcrumb.querySelector(".breadcrumb-cat");
  if (catLink) {
    catLink.addEventListener("click", e => {
      e.preventDefault();
      const cat = catLink.dataset.cat;
      currentCategory = cat;
      updateNavActive();
      goHome();
    });
  }

  // Related posts
  renderRelated(post);

  // Push ads
  try {
    (window.adsbygoogle = window.adsbygoogle || []).push({});
    (window.adsbygoogle = window.adsbygoogle || []).push({});
    (window.adsbygoogle = window.adsbygoogle || []).push({});
  } catch(e) {}

  // Start TOC highlighting
  startTocHighlighting();
}

function goHome() {
  currentPostId = null;
  postView.classList.add("hidden");
  homeView.classList.remove("hidden");
  heroEl.classList.remove("hidden");
  document.title = "JS · Playwright · TypeScript — Learning Hub | Basics to Architect | Free 2026";
  history.pushState(null, "", window.location.pathname);
  renderHome();
  window.scrollTo(0, 0);
}

/* ── Related Posts ────────────────────────────────────── */
function renderRelated(currentPost) {
  const all = loadPosts();
  const related = all
    .filter(p => p.id !== currentPost.id)
    .map(p => {
      let score = 0;
      if (p.category === currentPost.category) score += 3;
      if ((p.level || "beginner") === (currentPost.level || "beginner")) score += 1;
      const sharedTags = p.tags.filter(t => currentPost.tags.includes(t));
      score += sharedTags.length * 2;
      return { post: p, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, 6)
    .map(r => r.post);

  relatedGrid.innerHTML = "";
  related.forEach(post => {
    const card = document.createElement("div");
    card.className = "related-card";
    card.innerHTML = `
      <div class="rc-cat">${escapeHtml(post.category)} · 📖 ${readTime(post.content)} min</div>
      <h3>${escapeHtml(post.title)}</h3>
      <p>${escapeHtml(post.excerpt)}</p>
    `;
    card.addEventListener("click", () => openPost(post));
    relatedGrid.appendChild(card);
  });
}

/* ── TOC Active Highlighting ─────────────────────────── */
let tocObserver = null;

function startTocHighlighting() {
  if (tocObserver) tocObserver.disconnect();

  const headingEls = pvBody.querySelectorAll("h2[id], h3[id]");
  if (headingEls.length === 0) return;

  tocObserver = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const id = entry.target.id;
        pvToc.querySelectorAll("a").forEach(a => {
          a.classList.toggle("active", a.getAttribute("href") === `#${id}`);
        });
      }
    });
  }, { rootMargin: "-80px 0px -60% 0px", threshold: 0 });

  headingEls.forEach(el => tocObserver.observe(el));
}

/* ── Reading Progress ────────────────────────────────── */
function updateReadingProgress() {
  if (postView.classList.contains("hidden")) {
    readingProgress.style.width = "0%";
    return;
  }
  const docHeight = document.documentElement.scrollHeight - window.innerHeight;
  if (docHeight <= 0) { readingProgress.style.width = "0%"; return; }
  const pct = Math.min(100, (window.scrollY / docHeight) * 100);
  readingProgress.style.width = pct + "%";
}

/* ── Back to Top ─────────────────────────────────────── */
function updateBackToTop() {
  if (window.scrollY > 400) {
    backToTop.classList.remove("hidden");
  } else {
    backToTop.classList.add("hidden");
  }
}

/* ── Event Listeners ─────────────────────────────────── */

// Navbar category filter
navLinks.addEventListener("click", e => {
  const link = e.target.closest(".nav-link");
  if (!link) return;
  e.preventDefault();
  currentCategory = link.dataset.filter || "All";
  updateNavActive();
  if (!postView.classList.contains("hidden")) goHome();
  else renderHome();
});

function updateNavActive() {
  navLinks.querySelectorAll(".nav-link").forEach(l => {
    l.classList.toggle("active", l.dataset.filter === currentCategory);
  });
}

// Level filter
document.querySelector(".hero-levels").addEventListener("click", e => {
  const btn = e.target.closest(".level-btn");
  if (!btn) return;
  document.querySelectorAll(".level-btn").forEach(b => b.classList.remove("active"));
  btn.classList.add("active");
  currentLevel = btn.dataset.level || "All";
  renderHome();
});

// Search
searchInput.addEventListener("input", renderHome);

// Hamburger
hamburger.addEventListener("click", () => {
  navLinks.classList.toggle("open");
});

// Back button in post view
pvBack.addEventListener("click", goHome);

// Back to top
backToTop.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));

// Scroll events
window.addEventListener("scroll", () => {
  updateReadingProgress();
  updateBackToTop();
}, { passive: true });

// Footer category links
document.querySelectorAll("[data-footer-filter]").forEach(link => {
  link.addEventListener("click", e => {
    e.preventDefault();
    currentCategory = link.dataset.footerFilter || "All";
    updateNavActive();
    goHome();
  });
});

// Logo → home
document.getElementById("nav-home").addEventListener("click", e => {
  e.preventDefault();
  currentCategory = "All";
  currentLevel = "All";
  updateNavActive();
  document.querySelectorAll(".level-btn").forEach(b => b.classList.toggle("active", b.dataset.level === "All"));
  goHome();
});

// Browser back/forward
window.addEventListener("popstate", () => {
  const hash = window.location.hash;
  if (hash.startsWith("#post/")) {
    const slug = hash.replace("#post/", "");
    const posts = loadPosts();
    const post = posts.find(p => slugify(p.title) === slug);
    if (post) { openPost(post); return; }
  }
  goHome();
});

/* ── Deep Link Handling ──────────────────────────────── */
function handleDeepLink() {
  const hash = window.location.hash;
  if (hash.startsWith("#post/")) {
    const slug = hash.replace("#post/", "");
    const posts = loadPosts();
    const post = posts.find(p => slugify(p.title) === slug);
    if (post) { openPost(post); return; }
  }
  // Check URL params for search
  const params = new URLSearchParams(window.location.search);
  const q = params.get("q");
  if (q) { searchInput.value = q; }
}

/* ── Initialize ──────────────────────────────────────── */
syncPostsFromSource();
renderHome();
handleDeepLink();
